import { config } from "dotenv";
config();

import { createTransport } from "nodemailer";

const USERNAME = process.env.MAIL_USERNAME;
// Password generated by Google on 2023 November
// Google Account > Security > 2F > App Passwords
const PASSWORD = process.env.MAIL_PASSWORD;

export const transporter = createTransport({
  host: "smtp.gmail.com",
  auth: {
    user: USERNAME,
    pass: PASSWORD,
  },
});

export const getRegisterCodeOptions = (to: string, code: number) => {
  return {
    from: USERNAME,
    to: to,
    subject: "NodeJS Server: Verification Code",
    text: `CODE: ${code}\nThanks for registration.`,
  };
};
